# Generated by Django 2.1.1 on 2018-12-02 04:06

import TLS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=TLS.models.user_directory_path, verbose_name='Attachment')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255, verbose_name='Name')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('content', models.TextField(verbose_name='Content')),
            ],
        ),
        migrations.CreateModel(
            name='newClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(blank=True, max_length=3000)),
                ('resultstring', models.CharField(blank=True, max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='submissionsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=512)),
                ('uploadNum', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=512)),
                ('comment', models.TextField(blank=True)),
                ('uploadPath', models.CharField(max_length=512)),
                ('numberOfFiles', models.CharField(max_length=512)),
                ('filenames', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='UploadData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=255)),
                ('req', models.CharField(max_length=255)),
                ('uploadNum', models.CharField(max_length=255)),
                ('uploadPath', models.CharField(max_length=512)),
                ('numberOfFiles', models.CharField(max_length=512)),
                ('userID', models.CharField(max_length=512)),
                ('filenames', models.CharField(max_length=3000)),
            ],
        ),
    ]
