# Generated by Django 2.1.1 on 2018-11-08 17:50

import TLS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TLS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=TLS.models.user_directory_path, verbose_name='Attachment'),
        ),
    ]
