# Generated by Django 2.1.1 on 2018-11-19 16:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TLS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psqlupload',
            name='queryArray',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=99),
        ),
    ]
