# Generated by Django 2.1.1 on 2018-11-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TLS', '0003_auto_20181119_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='psqlupload',
            name='uploadNumber',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
