# Generated by Django 2.1.1 on 2018-11-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TLS', '0004_psqlupload_uploadnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='psqlupload',
            name='querysearch',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='psqlupload',
            name='searchvector',
            field=models.TextField(blank=True),
        ),
    ]
