# Generated by Django 2.1.1 on 2018-11-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TLS', '0006_auto_20181108_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author_email',
        ),
        migrations.RemoveField(
            model_name='message',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.AddField(
            model_name='message',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
