# Generated by Django 2.1.1 on 2018-11-20 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TLS', '0006_auto_20181120_0248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newclass',
            old_name='filenames',
            new_name='resultstring',
        ),
        migrations.RenameField(
            model_name='newclass',
            old_name='uploaduser',
            new_name='string',
        ),
    ]
