# Generated by Django 2.1.1 on 2018-11-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TLS', '0002_auto_20181108_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
