# Generated by Django 2.1.1 on 2018-11-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TLS', '0002_uploaddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddata',
            name='numberOfFiles',
            field=models.CharField(default=0, max_length=512),
            preserve_default=False,
        ),
    ]
