# Generated by Django 2.1.1 on 2018-11-19 16:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TLS', '0002_auto_20181119_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psqlupload',
            name='queryArray',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None),
        ),
    ]
