# Generated by Django 2.1.1 on 2018-11-10 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TLS', '0003_attachment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='count',
        ),
    ]
