# Generated by Django 2.1.1 on 2018-11-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TLS', '0004_uploaddata_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddata',
            name='filenames',
            field=models.CharField(default=0, max_length=3000),
            preserve_default=False,
        ),
    ]
