# Generated by Django 2.1.1 on 2018-11-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TLS', '0004_remove_attachment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
