# Generated by Django 2.1.1 on 2018-11-18 22:06

from django.conf import settings
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TLS', '0005_uploaddata_filenames'),
    ]

    operations = [
        migrations.CreateModel(
            name='postgresModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('userID', models.CharField(blank=True, max_length=255)),
                ('searchTerm', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='psqlUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=512)),
                ('filename', models.CharField(max_length=255)),
                ('querystring', models.CharField(max_length=255)),
                ('resultset', models.CharField(max_length=255)),
                ('reqTestedOn', models.CharField(max_length=512)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
