# Generated by Django 2.1.1 on 2018-11-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TLS', '0005_auto_20181120_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psqlupload',
            name='querysearch',
            field=models.CharField(max_length=3000),
        ),
    ]
