# Generated by Django 2.1.1 on 2018-11-18 22:09

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TLS', '0006_postgresmodel_psqlupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postgresmodel',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='psqlupload',
            name='resultset',
        ),
        migrations.AddField(
            model_name='psqlupload',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
