# Generated by Django 2.1.1 on 2018-11-18 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TLS', '0007_auto_20181118_2209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='postgresModel',
        ),
    ]
