# Generated by Django 2.1.1 on 2018-11-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TLS', '0008_delete_postgresmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psqlupload',
            name='querystring',
            field=models.TextField(),
        ),
    ]
