# Generated by Django 2.1.1 on 2018-11-18 23:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TLS', '0009_auto_20181118_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psqlupload',
            name='querystring',
        ),
        migrations.AddField(
            model_name='psqlupload',
            name='queryArray',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), default=2, size=None),
            preserve_default=False,
        ),
    ]
