# Generated by Django 2.1.1 on 2018-12-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TLS', '0009_auto_20181201_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionsmodel',
            name='user',
            field=models.CharField(max_length=512),
        ),
    ]
