# Generated by Django 2.1.1 on 2018-12-02 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TLS', '0010_auto_20181201_2304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PSQLUpload',
        ),
    ]
