# Generated by Django 2.1.1 on 2018-11-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TLS', '0011_auto_20181108_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='documents/', verbose_name='Attachment'),
        ),
    ]
