# Generated by Django 2.1.1 on 2018-11-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='CustomUser_slug',
            field=models.SlugField(default=0, max_length=30, verbose_name='user slug'),
            preserve_default=False,
        ),
    ]
