# Generated by Django 2.1.1 on 2018-11-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_customuser_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='uploads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
