# Generated by Django 2.1.1 on 2018-11-09 03:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_uploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uploads',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
